// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tools

import "encoding/json"
import "fmt"

type GrepFileParamsJson struct {
	// 大文字小文字を区別するかどうか
	CaseSensitive bool `json:"case_sensitive" yaml:"case_sensitive" mapstructure:"case_sensitive"`

	// 検索するキーワード
	Keyword string `json:"keyword" yaml:"keyword" mapstructure:"keyword"`

	// 検索を開始するディレクトリのパス
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrepFileParamsJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["case_sensitive"]; raw != nil && !ok {
		return fmt.Errorf("field case_sensitive in GrepFileParamsJson: required")
	}
	if _, ok := raw["keyword"]; raw != nil && !ok {
		return fmt.Errorf("field keyword in GrepFileParamsJson: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in GrepFileParamsJson: required")
	}
	type Plain GrepFileParamsJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrepFileParamsJson(plain)
	return nil
}
