// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tools

import "encoding/json"
import "fmt"

type ListFileParamsJson struct {
	// 一覧を取得するディレクトリのパス
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListFileParamsJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ListFileParamsJson: required")
	}
	type Plain ListFileParamsJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListFileParamsJson(plain)
	return nil
}
