// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package tools

import "encoding/json"
import "fmt"

type ReadFileParamsJson struct {
	// 読み込むファイルのパス
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadFileParamsJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ReadFileParamsJson: required")
	}
	type Plain ReadFileParamsJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ReadFileParamsJson(plain)
	return nil
}
